name: CI

on:
  pull_request:
  schedule:
    # NOTE: We run this weekly at 1 am UTC on every Saturday
    - cron:  '0 1 * * 6'

jobs:
  # This is based on this workflow, with an additional test env setup method
  # StackStorm-Exchange/ci/.github/workflows/pack-build_and_test.yaml@master
  build_and_test:
    name: 'Build and Test ${{ matrix.python-version }}'
    strategy:
      matrix:
        include:
          - python-version-short: "3.8"
            python-version: 3.8.18
          - python-version-short: "3.9"
          - python-version: 3.9.18
          - python-version-short: "3.10"
          - python-version: 3.10.13
    uses: StackStorm-Exchange/ci/.github/workflows/pack-build_and_test.yaml@master
    with:
      enable-common-libs: true
      #apt-cache-version: v0
      #py-cache-version: v0
